version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: N@123
      MYSQL_DATABASE: agriculture
    ports:
      - "3306:3306"

  backend:
    build: ./backend/demo
    container_name: spring-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/agriculture
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: N@123
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build: ./frontend/frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
